### ISSUE TITLE
#113 - #123

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#117]
- [x] source
- [x] windows 3.1
- [x] windows 3.2
- [x] mavericks 3.1
- [x] mavericks 3.2
- [x] binaries to AWS mac
- [x] binaries to AWS win

**Comment by ldecicco-USGS** [comment]
I'm doing it by hand because of usgsEGRET not matching the repo name...and not building the vignettes.

**Comment by ldecicco-USGS** [comment]
Source up, binaries in the morning

**Comment by jread-usgs** [comment]
hmm...shouldn't be able to compile mda.streams or powstreams without an update to `result` vs `loadOutput` for geoknife. we'll need an update for those two.

**Comment by ldecicco-USGS** [comment]
@jread-usgs

**Comment by jread-usgs** [comment]
I will try 3.1 again, but it failed kind of weirdly a couple of times. 3.2 is up

**Comment by jread-usgs** [comment]
mac is all good @ldecicco-USGS
