### ISSUE TITLE
--no-build-vignettes --no-manual

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#119]
Did we decide to implement this?

**Comment by lawinslow** [comment]
Implement it as in not build vignettes or to build them?

**Comment by ldecicco-USGS** [comment]
I can change https://github.com/USGS-R/grantools/blob/master/dl_build_src_gran.R#L46 to:

```
cmd = paste0('R CMD build ', pkgdirname, ' --no-build-vignettes --no-manual')
```
Correct? (so we don't build them)

**Comment by lawinslow** [comment]
Yeah, not sure why that wasn't already changed.
