### ISSUE TITLE
Packages that depend on GRAN packages

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#19]
I'm having trouble compiling glmtools because it depends on GLMr. The order in the text file seems right, and I think I figured out a way to do it last time (only a problem on the Mac) - but we should figure out a way to harden the script to not have to do any fiddling.

**Comment by lawinslow** [comment]
Doesn't [this line](https://github.com/USGS-R/grantools/blob/master/dl_build_src_gran.R#L8) prevent that issue?

**Comment by ldecicco-USGS** [comment]
Things all work correctly on my Windows computer. Things all don't work on my Mac. Is GLMr right now the only package with a GRAN dependency? I'll poke around later.

**Comment by lawinslow** [comment]
Weird. Yeah, glmtools is probably the only package right now with a GRAN-only dependency. GLMr should have no GRAN dependencies though.

**Comment by ldecicco-USGS** [comment]
Oh right. glmtools is what I meant, it depends on GLMr

**Comment by jread-usgs** [comment]
we are good now on this, right?

**Comment by ldecicco-USGS** [comment]
Let's not close it yet. I had to do a lot of futzing when updating to 3.2. Basically, one-by-one package updates to gran, in the right order. I'm sure there's a better way.

**Comment by jread-usgs** [comment]
oh, I see. This is still an issue then. And is related to our earlier convo.

**Comment by jread-usgs** [comment]
Odd that it worked for me on mac though. I didn't have the swmr pkgs on 3.2, and the build worked until it hit the powstreams error.

**Comment by ldecicco-USGS** [comment]
Because it was up on GRAN. So, once they are up, it's fine. You can't put 2 packages up at once, where one depends on the other. Maybe that's just life.

**Comment by lawinslow** [comment]
What's the process like on CRAN? I have a feeling it has the same issue if I were to guess.

**Comment by lawinslow** [comment]
Emailed Uwe, Brian and Kurt to see how CRAN does it. While writing the email, I realized it may not be impossible to create a directed graph of dependencies and traverse it in the proper order. Would also need to change how dependencies are installed (can't install from GRAN, would need to install from recently built packages locally... hmm...)

**Comment by lawinslow** [comment]
Ok, reply from Brian was terse, as I should have expected. But based on his response, and some further reflection, we can solve this problem by not using binary packages for dependencies, rather, use the source packages. They build without needing dependencies. 

Likely need to change how (dependencies are installed)[https://github.com/USGS-R/grantools/blob/master/dl_build_src_gran.R#L40].

**Comment by jread-usgs** [comment]
can you forward email to our email accounts? just curious. but yes, this seems to make sense..?
