### ISSUE TITLE
Temp folder needs clearing out?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#24]
I updated the sources packages, and subsequently realized I had forgotten to update my version number in the description file in EGRETci. So, I updated that, cut a new release of EGRETci, updated the version in grantools...and had issues building the source. In the temp file folder, there were 2 versions of EGRETci, the old one and the new one (which naturally took me a while to troubleshoot what the heck was going on). So, maybe we can clean out the temp file after each round of the build?

Maybe:

``` r
unlink(scratch, recursive=TRUE)
```

Next time I mess with this I'll see how it works (unless someone else takes the ball and runs).

**Comment by ldecicco-USGS** [comment]
still an issue. I think only on the Mac

**Comment by lawinslow** [comment]
Interesting. Unlink might help address this issue (though I still wish I knew exactly what was going on, new downloads should overwrite old ones, hrmmm).

Want to try adding this around line 29? 

```
unlink(file.path(scratch,'*'), recursive=TRUE)
```

That way, we don't delete the folder itself, just what is contained within the folder.
