### ISSUE TITLE
remove http

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/grantools#247]
![image](https://cloud.githubusercontent.com/assets/13987349/18020643/0f551dfa-6ba8-11e6-9afe-4b4052d887cc.png)

**Comment by ldecicco-USGS** [comment]
Here maybe?
https://github.com/USGS-R/grantools/blob/master/R/jenkins_build_bin.R#L8

**Comment by lawinslow** [comment]
Yup, those should be fixed.

**Comment by lawinslow** [comment]
I think that's the only place. 

We should also remove these s3 references as well.
https://github.com/USGS-R/grantools/blob/e496a85fbededa79d7599f91ec9a21c34fd80593/R/jenkins_build_bin.R#L27

We don't use R for S3 sync

**Comment by wdwatkins** [comment]
@lawinslow can we get rid of the `sync` argument as well then?
https://github.com/USGS-R/grantools/blob/master/R/build_bin.R#L85

**Comment by lawinslow** [comment]
Yeah, drop them. We don't use them. Not the right code anymore anyway.
