### ISSUE TITLE
Talk to rOpenSci?

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#277]
https://ropensci.org/blog/2015/08/04/a-drat-repository-for-ropensci/

**Comment by ldecicco-USGS** [comment]
https://github.com/ropensci/drat

**Comment by wdwatkins** [comment]
https://github.com/richfitz/drat.builder

**Comment by wdwatkins** [comment]
R s3 client: https://github.com/cloudyr/aws.s3

**Comment by wdwatkins** [comment]
Drat seems to be based on automatically building nightly the latest master version of every repo in their organization, so I seems like its more intended to replace devtools github installs.  I think we want to GRAN to be a bit more selective than that, and only be updated with tagged releases.  Perhaps drat could be adapted for this, although I'm not sure what we would gain at this point

**Comment by wdwatkins** [comment]
drat.builder could potentially be useful, not sure if it deals with dependencies though.

**Comment by lindsaycarr** [comment]
Another useful feature of ROpenSci's setup is that with the AWS stuff, they are able to parse the download logs and summarize some stats for who/when/where packages are being downloaded.

**Comment by ldecicco-USGS** [comment]
Luke had a script to do that, but off-hand I don't remember where the script was left (and it might have been specific to the CAWS bucket vs CHS....). Anyway, if I can't easily find his scripts, we'll probably just use those.

**Comment by wdwatkins** [comment]
@lindsaycarr what package was that in?

**Comment by lindsaycarr** [comment]
@wdwatkins it's the `parse_s3_logs.R` script located in rOpenSci's `drat` repo
