### ISSUE TITLE
Email on error

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#308]
ERROR: Could not connect to SMTP host: localhost, port: 25
javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;

@jiwalker-usgs do you know how to get it to send us an email if the job fails?

**Comment by jiwalker-usgs** [comment]
This is a windows specific issue I think.  Basically rather than localhost smtp it should be pointing to the bison connect smtp, but that probably requires authentication.  It might be easier to enable slack integration for failures :(
