### ISSUE TITLE
Set up 3.2

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/grantools#38]

**Comment by ldecicco-USGS** [comment]
How are we going to do this on the Mac? In Windows I can easily jump from version to version...

**Comment by ldecicco-USGS** [comment]
I think the dependencies need to be on GRAN first. So I need to do this in batches.

**Comment by ldecicco-USGS** [comment]
That didn't solve the problem, grrrr.....

**Comment by ldecicco-USGS** [comment]
It might be that `powstreams` imports `httr`, which is being used in the script. That wasn't a problem before, but now only `powstreams` is giving me issues.

**Comment by ldecicco-USGS** [comment]
If I step through by hand, and don't run `install_deps(pkgdirname)` for `powstreams`, it works. Clearly not a sustainable solution, but will get the 3.2 packages up there for now.

**Comment by ldecicco-USGS** [comment]
Aaaaaaannnnnnddddd the exact same issue on the Mac.

**Comment by jread-usgs** [comment]
Do we need to get a few of us to hammer out a sustainable solution here?

**Comment by ldecicco-USGS** [comment]
Yes. Yes we do.

**Comment by jread-usgs** [comment]
For the record, this is an issue with a poorly formatted DESCRIPTION file. 

`Error in isNamespaceLoaded(pkg) : 
  attempt to use zero-length variable name`

in `devtools`:
```R
pkg <- as.package(pkg)
    deps <- identical(dependencies, NA)
    deps <- unlist(pkg[tolower(deps)], use.names = FALSE)
    parse_deps(paste(deps, collapse = ","))
```
parses a hanging comma to be an additional package. So you get unlist as
`"\nR (>= 3.0),"                                          "\nmda.streams,\nsbtools,\ndplyr,\nhttr,\ndataRetrieval"`
which becomes `"\nR (>= 3.0),,\nmda.streams,\nsbtools,\ndplyr,\nhttr,\ndataRetrieval"`
adding an empty field.

**Comment by jread-usgs** [comment]
because of 
```YAML
Depends:
    R (>= 3.0),
Imports:
    mda.streams
```
but this seeeeeems to silently fail on windows, but error on mac. odd
