### ISSUE TITLE
package dependencies not installed automatically

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/grantools#47]
dealing w/ this when I switch R versions and don't have all dependencies locally. I would think the script would be installing deps, but no dice?

**Comment by lawinslow** [comment]
Should be, unless someone removed it. In fact, the goal is to install all dreps from scratch and *not* use your locally installed dependencies.

**Comment by jread-usgs** [comment]
@ldecicco-USGS had same issue. Let's check in on this next week.

**Comment by lawinslow** [comment]
It's in dl_build_src.
