### ISSUE TITLE
package binaries for PR #55

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/grantools#56]
- [x] windows 3.1
- [x] windows 3.2
- [x] mavericks 3.1
- [x] mavericks 3.2
- [x] binaries to AWS

**Comment by ldecicco-USGS** [comment]
This is now for #57

**Comment by jread-usgs** [comment]
now #57

**Comment by ldecicco-USGS** [comment]
Yup

**Comment by jread-usgs** [comment]
Say go when we are done doing PRs today

**Comment by ldecicco-USGS** [comment]
I'm done.

**Comment by jread-usgs** [comment]
I'm done too

**Comment by jread-usgs** [comment]
@ldecicco-USGS mac is done
