### ISSUE TITLE
Pull request #66

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/grantools#67]
https://github.com/USGS-R/grantools/pull/66

- [x] source
- [x] windows 3.1
- [x] windows 3.2
- [x] mavericks 3.1
- [x] mavericks 3.2
- [x] binaries to AWS

**Comment by jread-usgs** [comment]
I am working on mac now

**Comment by jread-usgs** [comment]
mavs is up on GRAN gdrive

**Comment by lawinslow** [comment]
Just put mavs on AWS.
