### ISSUE TITLE
Pull request 68

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-R/grantools#69]
https://github.com/USGS-R/grantools/pull/68

- [x] source
- [x] windows 3.1
- [x] windows 3.2
- [x] mavericks 3.1
- [x] mavericks 3.2
- [x] binaries to AWS

**Comment by jread-usgs** [comment]
mavs up on gdrive

**Comment by jread-usgs** [comment]
bump

**Comment by lawinslow** [comment]
@mhines-usgs is there a different update from this morning?

**Comment by lawinslow** [comment]
@mhines-usgs if 2.0.4 is current, you can close this

**Comment by mhines-usgs** [comment]
👍👏
