### ISSUE TITLE
PR #71 tasks

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/grantools#72]
#71 

- [x] source
- [x] windows 3.1
- [x] windows 3.2
- [x] mavericks 3.1
- [x] mavericks 3.2
- [x] binaries to AWS mac
- [x] binaries to AWS win

**Comment by jread-usgs** [comment]
all set for mac @ldecicco-USGS. Upload is ongoing, should be complete in 2 mins or so

**Comment by ldecicco-USGS** [comment]
I think the rest are @lawinslow 's gran-bot. Right?

**Comment by lawinslow** [comment]
Yeah, I thought I checked those off. What's up github?

**Comment by jread-usgs** [comment]
I noticed that too. i thought it was because I had it open in another window and was editing too...
