### ISSUE TITLE
PR 78

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/grantools#79]
#80

- [x] source
- [x] windows 3.1
- [x] windows 3.2
- [x] mavericks 3.1
- [x] mavericks 3.2
- [x] binaries to AWS mac
- [x] binaries to AWS win

**Comment by jread-usgs** [comment]
now applies to #80

**Comment by lawinslow** [comment]
ok, running

**Comment by jread-usgs** [comment]
I am on mac

**Comment by jread-usgs** [comment]
mac is up on drive for both

**Comment by lawinslow** [comment]
@jread-usgs Where on drive?

**Comment by jread-usgs** [comment]
https://drive.google.com/drive/folders/0Bz67-i1wbg6JTlFpMXk1a0Rla2M can you see that?

**Comment by lawinslow** [comment]
Oh yeah, got it. Was looking at the "last updated" at the folder level. Still said Feb 3rd.
